//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperbackCiamOTP.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OtpErrorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OtpErrorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuperbackCiamOTP.Resources.OtpErrorResources", typeof(OtpErrorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Type: {0}. .
        /// </summary>
        internal static string ChannelType {
            get {
                return ResourceManager.GetString("ChannelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsDeleteRedisStatus: {0} .
        /// </summary>
        internal static string IsDeleteRedisStatus {
            get {
                return ResourceManager.GetString("IsDeleteRedisStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsSaveRedisStatus: {0}, TypeSend: {1}. .
        /// </summary>
        internal static string IsSaveRedisStatus {
            get {
                return ResourceManager.GetString("IsSaveRedisStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Code:{0} \n Message:{1} \n Is Development:{2}. .
        /// </summary>
        internal static string MiddlewareException {
            get {
                return ResourceManager.GetString("MiddlewareException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OtpTypeError: {0}. .
        /// </summary>
        internal static string OtpTypeError {
            get {
                return ResourceManager.GetString("OtpTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otp type not supported yet. .
        /// </summary>
        internal static string OtpTypeNotSupported {
            get {
                return ResourceManager.GetString("OtpTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redis Error: {0}.
        /// </summary>
        internal static string RedisError {
            get {
                return ResourceManager.GetString("RedisError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider: {0} :  ResponseError: {1}. .
        /// </summary>
        internal static string ResponseError {
            get {
                return ResourceManager.GetString("ResponseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendOtpError: Channel type not supported yet. .
        /// </summary>
        internal static string SendOtpError {
            get {
                return ResourceManager.GetString("SendOtpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimpleEmailException:{0} .
        /// </summary>
        internal static string SimpleEmailException {
            get {
                return ResourceManager.GetString("SimpleEmailException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider: {0} :  SingleSendError: {1}. .
        /// </summary>
        internal static string SingleSendError {
            get {
                return ResourceManager.GetString("SingleSendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Error : {0}. .
        /// </summary>
        internal static string SmsError {
            get {
                return ResourceManager.GetString("SmsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TemplateEmailException:{0} .
        /// </summary>
        internal static string TemplateEmailException {
            get {
                return ResourceManager.GetString("TemplateEmailException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider: {0} :  CreateTemplateError: {1}. .
        /// </summary>
        internal static string TemplateError {
            get {
                return ResourceManager.GetString("TemplateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        internal static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
    }
}
