name: Autogenerar Changelog
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Generate Changelog
      id: changelog
      run: |
        echo "Generating changelog..."
        npm install -g conventional-changelog-cli
        changelog=$(conventional-changelog -p angular)
        echo "::set-output name=changelog::$changelog"
