name: Generate Changelog

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate Changelog
      run: git log --pretty=format:"- %s" | tee changelog.md
 
