name: Autogenerar Changelog
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Generate Changelog
      uses: saadmk11/changelog-ci@v1.1.1
