name: Autogenerar Changelog
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Generate Changelog
      run: |
          echo "Generating changelog..."
          changelog=$(git log --pretty=format:"- %s" $(git describe --tags --abbrev=0)..HEAD)
          echo "## Changelog" > changelog.md
          echo "${changelog}" >> changelog.md
          echo "Changelog generated."

    - name: Actualizar rama main
      run: |
          git checkout main
          if [[ -n $(git status -s) ]]; then
              git add changelog.md
              git -c user.name="Alejandro Yee Flores" -c user.email="alejandro.yee@digitalfemsa.com" commit -m "Updated changelog"
              git push origin main
          else
             echo "No hay cambios para actualizar en la rama main."
          fi
