name: Autogenerar Changelog
on:
  push:
    branches:
      - main

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Generate Changelog
      id: changelog
      run: |
        echo "Generating changelog..."
        
        changelog=$(git log --pretty=format:"- %s" $(git describe --tags --abbrev=0)..HEAD)
        echo "::set-output name=changelog::$changelog"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.sha }}
        release_name: Release ${{ github.sha }}
        body: ${{ steps.changelog.outputs.changelog }}
