name: Validar Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  validation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Verificar título y descripción
        run: |
          title_regex="^(feat|fix|hotfix|bug|doc)\/[A-Z]{2,5}-\d{2,5}:\s.+"
          description_regex="^(develop|feature|hotfix|release)\/[a-zA-Z]+-[0-9]+-.*"
          
          if ! [[ "${{ github.event.pull_request.title }}" =~ $title_regex ]]; then
            echo "El título del pull request no cumple con el formato especificado."
            exit 1
          fi
          
          if ! [[ "${{ github.event.pull_request.body }}" =~ $description_regex ]]; then
            echo "La descripción del pull request no cumple con el formato especificado."
            exit 1
          fi
