name: Validar Pull Request
on:
  pull_request_target:
    types:
      - opened
      - synchronize
jobs:
  validation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Verificar título y descripción
        run: |
          title_regex="^(\[DEVELOP\]|\[FEATURE\]|\[HOTFIX\]|\[RELEASE\]) [a-zA-Z0-9]+.*"
          title="${{ github.event.pull_request.title }}"
          description="${{ github.event.pull_request.body }}"
          
          echo "Título del pull request: $title"

          if ! [[ "${{ github.event.pull_request.title }}" =~ $title_regex ]]; then
            echo "El título del pull request no cumple con el formato especificado."
            exit 1
          fi
          
          if [[ -z "$description" ]]; then
            echo "La descripción del pull request está vacía."
            exit 1
          fi
